# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField()),
                ('prix', models.TextField()),
                ('km', models.TextField()),
                ('type_voiture', models.TextField()),
                ('transmission', models.TextField()),
                ('couleur_ext', models.TextField()),
                ('couleur_int', models.TextField()),
                ('moteur', models.TextField()),
                ('puissance', models.TextField()),
                ('type_essence', models.TextField()),
                ('plus', models.TextField()),
                ('options', models.TextField()),
                ('photo1', models.FileField(upload_to='')),
                ('date_ajout', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
