# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vav', '0002_auto_20151231_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voiture',
            name='couleur_ext',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='couleur_int',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='km',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='moteur',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='options',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='photo1',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='plus',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='prix',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='puissance',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='titre',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='transmission',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='type_essence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='type_voiture',
            field=models.TextField(blank=True),
        ),
    ]
