# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vav', '0005_voiture_date_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='titre_vignette',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
