# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vav', '0006_voiture_titre_vignette'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiture',
            name='options',
        ),
        migrations.AddField(
            model_name='voiture',
            name='annee',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='options_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voiture',
            name='options_2',
            field=models.TextField(blank=True),
        ),
    ]
