# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vav', '0007_auto_20151231_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='photo10',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='voiture',
            name='photo11',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='voiture',
            name='photo12',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='voiture',
            name='photo2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='voiture',
            name='photo3',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='voiture',
            name='photo4',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='voiture',
            name='photo5',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='voiture',
            name='photo6',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='voiture',
            name='photo7',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='voiture',
            name='photo8',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='voiture',
            name='photo9',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
