# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vav', '0009_auto_20151231_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='voiture',
            name='index',
            field=models.BooleanField(default=False),
        ),
    ]
